name: Test

on:
  push:
  pull_request:
    branches: [master]
    paths-ignore:
      - '*.md'
      - 'lib/fluent/version.rb'
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']
        ruby-version: ['3.4', '3.3', '3.2']
    name: Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@472790540115ce5bd69d399a020189a8c87d641f # v1.247.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install addons
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install libgmp3-dev libcap-ng-dev
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test TESTOPTS="-v --no-show-detail-immediately"
